export const STR = {
  appTitle: 'עורך וידאו',
  tabs: {
    batch: 'עיבוד חדש',
    results: 'תוצאות',
    assets: 'אפליקציות',
  },
  status: {
    queued: 'ממתין',
    downloading: 'מוריד',
    processing: 'מעבד',
    captioning: 'יוצר כיתוב',
    done: 'הושלם',
    failed: 'נכשל',
  },
  batch: {
    addRow: '+ הוסף סרטון',
    removeRow: 'הסר',
    asset: 'אפליקציה',
    outro: 'סגיר',
    sourceUpload: 'קובץ',
    sourceUrl: 'לינק',
    urlPlaceholder: 'https://... (לינק ישיר או יוטיוב/טיקטוק)',
    cutSeconds: 'שניית חיתוך',
    cutHint: 'הסרטון יישמר מההתחלה ועד לשנייה הזו, ומיד אחריה יתווסף הסגיר',
    send: 'שלח לעיבוד',
    sending: 'שולח...',
    selectAsset: 'בחר אפליקציה',
    selectOutro: 'בחר סגיר',
    noOutros: 'אין סגירים לאפליקציה הזו — העלה סגיר בטאב האפליקציות',
    noAssets: 'עדיין אין אפליקציות. עבור לטאב "אפליקציות" כדי להוסיף אחת.',
    errMissingAsset: 'יש לבחור אפליקציה בכל השורות',
    errMissingOutro: 'יש לבחור סגיר בכל השורות',
    errMissingSource: 'יש לבחור קובץ או להזין לינק בכל השורות',
    errMissingCut: 'יש להזין שניית חיתוך גדולה מ-0 בכל השורות',
    sentOk: 'הבאצ׳ נשלח! העיבוד התחיל.',
  },
  results: {
    empty: 'אין עדיין תוצאות. שלח באצ׳ מהטאב "עיבוד חדש".',
    batchTitle: 'באצ׳',
    download: 'הורדה',
    copyCaption: 'העתק כיתוב',
    copied: 'הועתק ✓',
    recaption: 'צור כיתוב מחדש',
    captionMissing: 'אין כיתוב (ניתן לנסות שוב)',
    refresh: 'רענן',
  },
  assets: {
    title: 'ניהול אפליקציות',
    name: 'שם האפליקציה',
    description: 'תיאור ואופי (משמש את הבינה ליצירת הכיתוב)',
    link: 'לינק שיווקי (חנות אפליקציות)',
    hashtags: 'האשטאגים (למשל ‎#app #fun)',
    create: 'הוסף אפליקציה',
    save: 'שמור',
    saved: 'נשמר ✓',
    delete: 'מחק',
    confirmDelete: 'למחוק את האפליקציה ואת כל הסגירים שלה?',
    outros: 'סגירים',
    uploadOutro: 'העלאת סגיר',
    deleteOutro: 'מחק סגיר',
    confirmDeleteOutro: 'למחוק את הסגיר?',
    noOutros: 'אין סגירים עדיין',
    empty: 'אין אפליקציות עדיין — הוסף את הראשונה:',
  },
  errors: {
    generic: 'שגיאה: ',
  },
}
