export const STR = {
  appTitle: 'עורך וידאו',
  tabs: {
    batch: 'עיבוד חדש',
    results: 'תוצאות',
    assets: 'אפליקציות',
    inbox: 'תיבת קלט',
    brief: 'בריף',
    review: 'סרטונים לאישור',
    approved: 'סרטונים שאושרו',
    published: 'סרטונים שעלו לרשת',
    log: 'יומן',
    more: 'עוד',
  },
  status: {
    queued: 'ממתין',
    downloading: 'מוריד',
    processing: 'מעבד',
    captioning: 'יוצר כיתוב',
    done: 'הושלם',
    failed: 'נכשל',
  },
  batch: {
    addRow: '+ הוסף סרטון',
    removeRow: 'הסר',
    asset: 'אפליקציה',
    outro: 'סגיר',
    intro: 'פתיח',
    noIntro: 'ללא פתיח',
    pickOutroTitle: 'בחירת סגיר — נגן כדי להתרשם ואז בחר',
    pickIntroTitle: 'בחירת פתיח — נגן כדי להתרשם ואז בחר',
    choose: 'בחר',
    uploadNewClip: '+ העלאת קליפ חדש',
    sourceUpload: 'קובץ',
    sourceUrl: 'לינק',
    urlPlaceholder: 'https://... (לינק ישיר או יוטיוב/טיקטוק)',
    startSeconds: 'משנייה (ריק = מההתחלה)',
    cutSeconds: 'עד שנייה (ריק = עד הסוף)',
    cutHint: 'נשמר הקטע שבין שניית ההתחלה לשניית הסיום — שדה ריק אומר בלי חיתוך באותו צד; פתיח (אם נבחר) לפניו, וסגיר מיד אחריו',
    errBadRange: 'שניית ההתחלה חייבת להיות קטנה משניית הסיום',
    send: 'שלח לעיבוד',
    sending: 'שולח...',
    selectAsset: 'בחר אפליקציה',
    selectOutro: 'בחר סגיר',
    noOutros: 'אין סגירים לאפליקציה הזו — העלה סגיר בטאב האפליקציות',
    noAssets: 'עדיין אין אפליקציות. עבור לטאב "אפליקציות" כדי להוסיף אחת.',
    errMissingAsset: 'יש לבחור אפליקציה בכל השורות',
    errMissingOutro: 'יש לבחור סגיר בכל השורות',
    errMissingSource: 'יש לבחור קובץ או להזין לינק בכל השורות',
    errBadCut: 'שניית הסיום חייבת להיות גדולה מ-0 (או ריקה — בלי חיתוך בסוף)',
    sentOk: 'הבאצ׳ נשלח! העיבוד התחיל.',
    sentOkGithub: 'הבאצ׳ נשלח! העיבוד רץ ב-GitHub Actions — התוצאות יופיעו בטאב התוצאות בעוד כמה דקות.',
  },
  results: {
    empty: 'אין עדיין תוצאות. שלח באצ׳ מהטאב "עיבוד חדש".',
    batchTitle: 'באצ׳',
    download: 'הורדה',
    copyCaption: 'העתק כיתוב',
    copied: 'הועתק ✓',
    recaption: 'צור כיתוב מחדש',
    captionMissing: 'אין כיתוב (ניתן לנסות שוב)',
    refresh: 'רענן',
    pendingBatch: 'באצ׳ בעיבוד',
    mockAlertTitle: '⚠️ לסרטונים האלה יש כיתוב זמני גנרי',
  },
  captions: {
    settingsTitle: 'כיתובים חכמים (Claude)',
    keyExplain:
      'הדביקו כאן מפתח API של Anthropic (מ-console.anthropic.com) והמערכת ' +
      'תיצור אוטומטית כיתוב ייחודי לכל סרטון לפי מה שרואים בו. המפתח נשמר ' +
      'רק בדפדפן שלכם.',
    keySet: 'מפתח שמור ✓ — כיתובים חכמים פעילים',
    keyMissing: 'אין מפתח שמור — הכיתובים יהיו גנריים',
    needKey: 'חסר מפתח Anthropic — פתחו את ההגדרות (⚙) והדביקו מפתח',
    alertBody:
      'כדי שכל סרטון יקבל כיתוב ייחודי לפי התוכן שלו: פתחו את ההגדרות (⚙), ' +
      'הדביקו מפתח Anthropic API, וחזרו לכאן — הכיתובים ייווצרו אוטומטית. ' +
      'אם כבר הדבקתם מפתח, לחצו על הכפתור.',
    runNow: 'צור כיתובים חכמים עכשיו',
    progress: 'יוצר כיתובים חכמים…',
    failed: 'יצירת הכיתובים נכשלה',
  },
  assets: {
    title: 'ניהול אפליקציות',
    name: 'שם האפליקציה',
    description: 'תיאור ואופי (משמש את הבינה ליצירת הכיתוב)',
    link: 'לינק שיווקי (חנות אפליקציות)',
    hashtags: 'האשטאגים (למשל ‎#app #fun)',
    create: 'הוסף אפליקציה',
    save: 'שמור',
    saved: 'נשמר ✓',
    delete: 'מחק',
    confirmDelete: 'למחוק את האפליקציה ואת כל הסגירים שלה?',
    clipsTitle: 'סגירים',
    uploadClip: 'העלאת סגיר',
    deleteClip: 'מחק סגיר',
    confirmDeleteClip: 'למחוק את הסגיר?',
    noClips: 'אין סגירים עדיין',
    empty: 'אין אפליקציות עדיין — הוסף את הראשונה:',
  },
  intros: {
    clipsTitle: 'פתיחים',
    uploadClip: 'העלאת פתיח',
    deleteClip: 'מחק פתיח',
    confirmDeleteClip: 'למחוק את הפתיח?',
    noClips: 'אין פתיחים עדיין',
  },
  errors: {
    generic: 'שגיאה: ',
  },
  scout: {
    inboxTitle: 'עמודי מקור לסריקה היומית',
    inboxExplain:
      'הסוכן סורק את העמודים הפעילים ברשימה פעם ביום ומאתר סרטונים שתואמים ' +
      'את הבריף.',
    addPage: 'הוסף עמודים',
    pageUrls: 'לינקים לעמודים (אחד בכל שורה)',
    pageUrlsPlaceholder: 'https://...\nhttps://...',
    pageAsset: 'אפליקציה (חובה)',
    errMissingAssetPage: 'חובה לשייך את העמודים לאפליקציה',
    errNoValidUrls: 'יש להזין לפחות לינק אחד (שורה שמתחילה ב-http)',
    addedCount: (n) => `נוספו ${n} עמודים ✓`,
    noAssetsYet: 'אין עדיין אפליקציות — הוסף אפליקציה בטאב "אפליקציות" לפני הוספת עמודים',
    allApps: 'כל האפליקציות',
    unknownAsset: 'ללא שיוך',
    discoverTitle: '🔍 חיפוש עמודים דומים ברשת',
    discoverDesc:
      'המערכת לומדת את העמודים שלך ומאתרת עמודים רשמיים של אפליקציות ' +
      'מאותו תחום — לא עמודים פרטיים או חובבי התחום. מה שכבר במעקב, ' +
      'הוצע בעבר או נדחה — לא יוצע שוב.',
    discoverBtn: 'חפש עכשיו',
    discoverRunning:
      'החיפוש יצא לדרך — הצעות חדשות יופיעו כאן בעוד כמה דקות (רענן את הדף).',
    dailyOn: 'חיפוש יומי: פעיל',
    dailyOff: 'חיפוש יומי: מושהה',
    dailyOnDesc: 'רץ אוטומטית כל בוקר וגם אחרי כל הוספת עמודים',
    dailyOffDesc: 'רץ רק בלחיצה על "חפש עכשיו"',
    pauseDaily: '⏸ עצור',
    resumeDaily: '▶ הפעל',
    skippedDup: (n) => `${n} כתובות שכבר במעקב דולגו`,
    suggestionsTitle: 'הצעות מהחיפוש ברשת',
    suggestionsHint: 'המערכת למדה את העמודים שלך ומצאה את הדומים האלה — אשר כדי להוסיף למעקב:',
    acceptSuggestion: 'הוסף למעקב',
    dismissSuggestion: 'לא מתאים',
    suggestionAccepted: 'נוסף למעקב ✓',
    active: 'פעיל',
    inactive: 'מושבת',
    toggleHint: 'לחיצה מפעילה/משביתה את הסריקה של העמוד',
    removePage: 'הסר',
    confirmRemovePage: 'להסיר את העמוד מהמעקב לגמרי? (אפשר גם רק להשבית בלחיצה על הסטטוס)',
    inboxEmpty: 'אין עדיין עמודים. הוסף עמוד ראשון כדי שהסוכן יתחיל לסרוק.',
    briefTitle: 'הבריף — קריטריוני ההתאמה של הסוכן',
    briefExplain:
      'הסוכן בוחר סרטונים, חותך ומכין קאפשן לפי מה שכתוב כאן. כתוב ' +
      'קריטריונים בדיקים, לא תיאור כללי.',
    briefSave: 'שמור בריף',
    briefSaved: 'הבריף נשמר ✓',
    briefConflict: 'הבריף השתנה בינתיים במקום אחר — רענן את הדף ונסה שוב',
    reviewExplain:
      'סרטונים חדשים שהסוכן הכין וממתינים להחלטה שלך. אישור מעביר לטאב ' +
      '"סרטונים שאושרו"; דחייה מסירה מכאן.',
    reviewEmpty: 'אין סרטונים חדשים לאישור. הסריקה הבאה תמלא את התור.',
    approvedExplain:
      'סרטונים שאישרת וממתינים להעלאה לרשת. פרסם עם הכפתורים, ואחרי ' +
      'שהעלית — סמן ✓ והסרטון יעבור לטאב "סרטונים שעלו לרשת".',
    approvedEmpty: 'אין סרטונים שממתינים להעלאה — כל מה שאישרת כבר עלה.',
    publishedExplain: 'הסרטונים שכבר עלו לרשת — התיעוד שלך, כדי לא להעלות פעמיים.',
    publishedEmpty: 'עדיין לא סומנו סרטונים שעלו לרשת.',
    approve: 'אשר ✓',
    reject: 'דחה ✗',
    rejectReason: 'סיבת הדחייה (לא חובה):',
    confirmUploaded: 'האם הסרטון עלה לרשת? הוא יעבור לטאב "סרטונים שעלו לרשת".',
    markUploadedBtn: '✓ העליתי את הסרטון לרשת',
    publishedAtLabel: 'עלה לרשת:',
    saveCaption: 'שמור קאפשן',
    captionSaved: 'הקאפשן נשמר ✓',
    videoUnavailable: 'קובץ הווידאו לא נמצא ב-Release',
    sourceLink: 'למקור ↗',
    logTitle: 'יומן העיבוד',
    logEmpty: 'היומן ריק — עדיין לא נסרקו סרטונים.',
    filterAll: 'הכל',
    lastRun: 'הריצה האחרונה',
    scanned: 'ביומן',
    statuses: {
      matched: 'תאם לבריף',
      rejected: 'נדחה',
      edited: 'נערך',
      pending_review: 'ממתין לאישור',
      approved: 'מאושר',
      published: 'פורסם',
      failed: 'נכשל',
    },
  },
  share: {
    share: '📤 שתף',
    uploadTo: 'העלאה ל:',
    openedWithCaption:
      'הכיתוב הועתק והסרטון בהורדה — גרור את הקובץ לחלון ההעלאה שנפתח והדבק את הכיתוב',
    opened: 'הסרטון בהורדה — גרור את הקובץ לחלון ההעלאה שנפתח',
    unsupported:
      'שיתוף ישיר לא נתמך בדפדפן הזה — השתמש בכפתורי הפלטפורמות (במובייל זה עובד הכי טוב)',
  },
  github: {
    settingsTitle: 'חיבור ל-GitHub',
    tokenExplain:
      'צפייה בתוצאות פתוחה לכולם, אבל שליחת סרטונים וניהול אפליקציות דורשים ' +
      'טוקן אישי של GitHub (נשמר רק בדפדפן שלך). יוצרים אותו פעם אחת:',
    createToken: 'יצירת טוקן חדש',
    tokenStep1: '(Fine-grained token) — תחת "Repository access" בחר "Only select repositories" ואת הריפו הזה.',
    tokenStep2: 'תחת "Permissions → Repository permissions" תן הרשאת Read and write ל-Contents ול-Actions.',
    tokenStep3: 'צור את הטוקן, העתק אותו והדבק כאן.',
    tokenSet: 'טוקן שמור ✓ — אפשר לשלוח סרטונים ולנהל אפליקציות',
    tokenMissing: 'אין טוקן שמור — אפשר רק לצפות בתוצאות',
    saveToken: 'שמור',
    clearToken: 'נתק',
    close: 'סגור',
    needToken: 'נדרש טוקן GitHub — לחץ על ⚙ למעלה והדבק טוקן',
    runFailed: 'הריצה נכשלה — פתח את הלוג ב-GitHub לפרטים',
    viewLog: 'צפה בלוג הריצה ↗',
    captionFailed: 'יצירת הכיתוב נכשלה',
  },
}
